name: time_forge
description: A time management and productivity app with a Terracotta theme.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2  # State management
  shared_preferences: ^2.3.2  # Save tasks/streaks
  fl_chart: ^0.68.0  # Analytics charts
  timer_count_down: ^2.2.2  # Pomodoro timers
  lottie: ^3.1.2  # Mascot animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/mascot/